# Schema for the configuration files of the xmlrpc_example module.

xmlrpc_example.server:
  type: config_object
  label: 'XML-RPC Server settings'
  mapping:
    min:
      type: integer
      label: 'Minimum value for example operations'
    max:
      type: integer
      label: 'Maximum value for example operations'
    alter_enabled:
      type: boolean
      label: 'Enable the method alterator'
